function queryHdr(inputHdr, inputNonBup){
            var newHdr = {
            CAR: inputHdr.CAR,
            KdKpbc: inputHdr.KdKpbc,
            PibNo: inputHdr.PibNo,
            PibTg: inputHdr.PibTg,
            JnPib: inputHdr.JnPib,
            JnImp: inputHdr.JnImp,
            JkWaktu: inputHdr.JkWaktu,
            CrByr: inputHdr.CrByr,
            DokTupKd: inputHdr.DokTupKd,
            DokTupNo: inputHdr.DokTupNo,
            DokTupTg: inputHdr.DokTupTg,
            PosNo: inputHdr.PosNo,
            PosSub: inputHdr.PosSub,
            PosSubSub: inputHdr.PosSubSub,
            ImpId: inputHdr.ImpId,
            ImpNpwp: inputHdr.ImpNpwp,
            ImpNama: inputHdr.ImpNama,
            ImpAlmt: inputHdr.ImpAlmt,
            ImpStatus: inputHdr.ImpStatus,
            ApiKd: inputHdr.ApiKd,
            ApiNo: inputHdr.ApiNo,
            PpjkId: inputHdr.PpjkId,
            PpjkNpwp: inputHdr.PpjkNpwp,
            PpjkNama: inputHdr.PpjkNama,
            PpjkAlmt: inputHdr.PpjkAlmt,
            PpjkNo: inputHdr.PpjkNo,
            PpjkTg: inputHdr.PpjkTg,
            IndId: inputHdr.IndId,
            IndNpwp: inputHdr.Npwp,
            IndNama: inputHdr.IndNama,
            IndAlmt: inputHdr.IndAlmt,
            PasokNama: inputHdr.PasokNama,
            PasokAlmt: inputHdr.PasokAlmt,
            PasokNeg: inputHdr.PasokNeg,
            PelBkr: inputHdr.PelBkr,
            PelMuat: inputHdr.PelMuat,
            PelTransit: inputHdr.PelTransit,
            TmpTbn: inputHdr.TmpTbn,
            Moda: inputHdr.Moda,
            AngkutNama: inputHdr.AngkutNama,
            AngkutNo: inputHdr.AngkutNo,
            AngkutFl: inputHdr.AngkutFl,
            TgTiba: inputHdr.TgTiba,
            KdVal: inputHdr.KdVal,
            Ndpbm: inputHdr.Ndpbm,
            NilInv: inputHdr.NillInv,
            Freight: inputHdr.Freight,
            BTambahan: inputHdr.BTambahan,
            Diskon: inputHdr.Diskon,
            KdAss: inputHdr.KdAss,
            Asuransi: inputHdr.Asuransi,
            KdHrg: inputHdr.KdHrg,
            Fob: inputHdr.Fob,
            Cif: inputHdr.Cif,
            Bruto: inputHdr.Bruto,
            Netto: inputHdr.Netto,
            JmCont: inputHdr.JmCont,
            JmBrg: inputHdr.JmBrg,
            Status: inputHdr.Status,
            Snrf: inputHdr.Snrf,
            KdFas: inputHdr.Kdfas,
            Lengkap: inputHdr.Lengkap,
            BillNpwp: inputHdr.BillNpwp,
            BillNama: inputHdr.BillNama,
            BillAlmt: inputHdr.BillAlmt,
            PenjualNama: inputHdr.PenjualNama,
            PenjualAlmt: inputHdr.PenjualAlmt,
            PenjualNeg: inputHdr.PenjualNeg,
            Pernyataan: inputHdr.Pernyataan,
            JnsTrans: inputHdr.JnsTrans,
            VD: inputHdr.VD,
            VersiModul: inputHdr.VersiModul,
            NilVd: inputHdr.NillVd,
            UserHistory: [inputNonBup.UserHistory]
            }
            return newHdr;
        }

module.exports = {
    queryHdr
}