const mongoose = require('mongoose');
const Schema = mongoose.Schema;


const tblPibNptSchema = new Schema({
    CAR: String,
    ResKd: String,
    RESTG: Date,
    RESWK: String,
    Asal: Number,
    BM_Asal: Number,
    CUK_Asal: Number,
    PPN_Asal: Number,
    PPNBM_Asal: Number,
    PPH_Asal: Number,
    Ditetapkan: Number,
    BMBYR: Number,
    CUKBYR: Number,
    PPNBYR: Number,
    PPNBMBYR: Number,
    PPHBYR: Number,
    DENDA: Number,
    Kurang: Number,
    BM_Kurang: Number,
    CUK_Kurang: Number,
    PPN_Kurang: Number,
    PPNBM_Kurang: Number,
    PPH_Kurang: Number,
    Lebih: Number,
    BM_Lebih: Number,
    CUK_Lebih: Number,
    PPN_Lebih: Number,
    PPNBM_Lebih: Number,
    PPH_Lebih: Number,
    JenisSalahDll: String,
    Total_Kurang: Number,
    Total_Lebih: Number,
    S_JnsBrg: String,
    S_JmlBrg:String,
    S_Tarif: String,
    S_NilPab: String,
    BMAD_Asal: Number,
    BMADBYR: Number,
    BMAD_KURANG: Number,
    BMAD_Lebih: Number,
    BMI_Asal: Number,
    BMIBYR: Number,
    BMI_KURANG: Number,
    BMI_Lebih: Number,
    BMTP_Asal: Number,
    BMTPBYR: Number,
    BMTP_KURANG: Number,
    BMTP_Lebih: Number,
    BMADS_Asal: Number,
    BMADSBYR: Number,
    BMADS_KURANG: Number,
    BMADS_Lebih: Number,
    BMIS_Asal: Number,
    BMISBYR: Number,
    BMIS_KURANG: Number,
    BMIS_Lebih:Number,
    BMTPS_Asal: Number,
    BMTPSBYR: Number,
    BMTPS_KURANG: Number,
    BMTPS_Lebih: Number,
    BMKT_Asal:Number,
    BMKT: Number,
    BMKT_KURANG: Number,
    BMKT_Lebih: Number
}, {timestampts:true})


const tblPibNpt = mongoose.model('tblPibNpt', tblPibNptSchema);

module.exports = tblPibNpt