const mongoose = require('mongoose');
const { ObjectId } = require('mongodb');
const Schema = mongoose.Schema;


const tblPibHdr = new Schema({
    CAR: String,
    KdKpbc: String,
    PibNo: String,
    PibTg: Date,
    JnPib: String,
    JnImp: String,
    JkWaktu: String,
    CrByr: String,
    DokTupKd: String,
    DokTupNo: Number,
    DokTupTg: Date,
    PosNo: String,
    PosSub: String,
    PosSubSub: String,
    ImpId: String,
    ImpNpwp: String,
    ImpNama: String,
    ImpAlmt: String,
    ImpStatus: String,
    ApiKd: String,
    ApiNo: String,
    PpjkId: String,
    PpjkNpwp: String,
    PpjkNama: String,
    PpjkAlmt: String,
    PpjkNo: String,
    PpjkTg: String,
    IndId: String,
    IndNpwp: String,
    IndNama: String,
    IndAlmt: String,
    PasokNama: String,
    PasokAlmt: String,
    PasokNeg: String,
    PelBkr: String,
    PelMuat: String,
    PelTransit: String,
    TmpTbn: String,
    Moda: String,
    AngkutNama: String,
    AngkutNo: String,
    AngkutFl: String,
    TgTiba: Date,
    KdVal: String,
    Ndpbm: Number,
    NilInv: Number,
    Freight: Number,
    BTambahan: Number,
    Diskon: Number,
    KdAss: String,
    Asuransi: Number,
    KdHrg: String,
    Fob: Number,
    Cif: Number,
    Bruto: Number,
    Netto: Number,
    JmCont: Number,
    JmBrg: Number,
    Status: String,
    Snrf: String,
    KdFas: String,
    Lengkap: String,
    BillNpwp: String,
    BillNama: String,
    BillAlmt: String,
    PenjualNama: String,
    PenjualAlmt: String,
    PenjualNeg: String,
    Pernyataan: String,
    JnsTrans: String,
    VD: String,
    VersiModul: String,
    NilVd: String,
    commodity: String,
    typeOfShipment: String,
    clearancePaymentStatus: Boolean,
    clearancePayments: [{type: ObjectId, ref:'TblCbu4wCCPaymentModel'}],
    remmitanceStatus: Boolean,
    userHistory:[]
}, {timestampts:true})

//boolean clearance payment cek qty total.
mongoose.model('TblPibHdr', tblPibHdr);

module.exports = tblPibHdr
